travis:
  secure:
    BINSTAR_TOKEN: pAaqo6xl5WdOjX/aWno+XjeRBaK3/hudPTOMZ0kWhRmiqwCYzAURioRKhpm4JbPAmGMo3GoaPMskQ88vDLDhyHbJ/jyziDvEHlgGQ35nvif6ss/YgxGU/eq0ItU+3YQY0VwSQRmZX+bP8NFStngFxsRiKjwFOhqJDBcj0je5I1JzPgI8ModQq2yV0kBYxD5cE9aoGzWiQJYwAb5aNyydvRMtcqQpHDRNV2io0mWhBTQjk688XoK0B4GUTQNTX+tHRxQEVvGKspPS/wrnrlkd6gpfE4IZDXekIAJwgaxNPvQ3xAHmuftBqlJAwZNbNPIm0TARPMcRsWPTwSQGEXx/aT+7sufu4jt1GrxbwogsOJFVqXT5OBAnDBzMBOwd9JFtelyWYM/fioHGhMmOTTwFcYCl/JkrlGMUrmLP1UAer4rAUPi5pj0JtYcQcaiXLR2hvqHLTJCtBYuTMGX9BK0vMmdqheBNkIccU3xWi6DuBvWxFwKoXZ3P0qzDGSyWdeSkGKuZerUrR6RBFVNDNLTsUYff+Hbb4LeUWfDnHEBbTJ4beRDg0MjH39z6R/o2dqzJwQwwRchubZRjkvSqUZ/d8I0yfuyqDHcjZlNS6+/VIuRX4JtglHIgft2+h9yUGI6/V8fUt+aUMtV/9rD3PE1o2HIarOpBcnQRBl3BYRvIVdU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
